apiVersion: v1
kind: Pod
metadata:
  name: secret-one-env-pod
spec:
  containers:
    - name: test-container
      image: pankajholariya/ibonginx
      envFrom:
      - secretRef:
          name: declaratively-secret
