apiVersion: v1
kind: Pod
metadata:
  name: secret-all-env-pod
spec:
  containers:
  - name: mycontainer
    image: pankajholariya/ibonginx
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: declaratively-secret
            key: username
            optional: false 
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: declaratively-secret
            key: password
            optional: false 