apiVersion: v1
kind: Pod
metadata: 
  name: secret-as-volume
spec: 
  containers: 
    - image: pankajholariya/ibonginx
      name: nginx
  volumes: 
    - name: dbcreds
      secret: 
        secretName: declaratively-secret